server.port=8181
# Configuration de la source de données
spring.datasource.url=jdbc:h2:mem:company_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
# ===============================
# HikariCP Connection Pool
# ===============================
# Nombre minimum de connexions inactives
spring.datasource.hikari.minimum-idle=2
# Nombre maximum de connexions dans le pool
spring.datasource.hikari.maximum-pool-size=5
# Timeout pour obtenir une connexion (ms)
spring.datasource.hikari.connection-timeout=30000
# Optionnel : durée de vie maximale d?une connexion (ms)
spring.datasource.hikari.max-lifetime=1800000
# Optionnel : intervalle de vérification des connexions inactives (ms)
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.auto-commit=false
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
# Forcer l'initialisation du pool Hikari pour H2
spring.datasource.hikari.pool-name=H2-HikariPool
# Pour accéder à l'interface graphique de la base
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.connection.autocommit=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=PUBLIC
#logging.level.org.springframework.security=DEBUG
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.event.merge.entity_copy_observer=allow
spring.jpa.show-sql=true
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true


management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
eureka.instance.prefer-ip-address=true
spring.config.import=optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}
eureka.client.service-url.defaultZone=${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}





eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# =========================
# SPRING CLOUD GATEWAY - DISCOVERY MODE
# =========================
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true



