server.port=8185
spring.application.name=facture
spring.datasource.url=jdbc:h2:mem:facture-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
# Pour accéder à l'interface graphique de la base
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.connection.autocommit=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=PUBLIC
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.event.merge.entity_copy_observer=allow
spring.jpa.show-sql=true
spring.devtools.restart.enabled=true
management.endpoints.web.exposure.include=health,info
eureka.client.service-url.defaultZone=${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true
spring.jpa.defer-datasource-initialization=true
